import { createServerClient, type CookieOptions } from '@supabase/ssr';
import { NextResponse, type NextRequest } from 'next/server';

type CookieToSet = { name: string; value: string; options?: CookieOptions };

const PUBLIC_PATHS = [
  '/',
  '/login',
  '/signup',
  '/auth/callback',
  '/privacy',
  '/terms',
  '/accessibility',
  '/counter',
  // File-based metadata generated by Next.js (favicon, OG, twitter card, etc.)
  '/opengraph-image',
  '/twitter-image',
  '/icon',
  '/apple-icon',
  '/manifest.webmanifest',
];

export async function middleware(request: NextRequest) {
  let response = NextResponse.next({ request });

  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return request.cookies.getAll();
        },
        setAll(cookiesToSet: CookieToSet[]) {
          cookiesToSet.forEach(({ name, value }) => request.cookies.set(name, value));
          response = NextResponse.next({ request });
          cookiesToSet.forEach(({ name, value, options }) =>
            response.cookies.set(name, value, options),
          );
        },
      },
    },
  );

  const { data: { user } } = await supabase.auth.getUser();
  const path = request.nextUrl.pathname;

  const isPublic =
    PUBLIC_PATHS.includes(path) ||
    path.startsWith('/_next/') ||
    path.startsWith('/api/') ||  // API routes handle their own auth
    // Metadata file routes (Next.js sometimes appends a hash, e.g. /opengraph-image-abc123)
    path.startsWith('/opengraph-image') ||
    path.startsWith('/twitter-image') ||
    path.startsWith('/icon') ||
    path.startsWith('/apple-icon') ||
    /\.(?:png|jpg|jpeg|svg|webp|ico|json|txt|webmanifest)$/i.test(path);

  if (!user && !isPublic) {
    const redirectUrl = new URL('/login', request.url);
    redirectUrl.searchParams.set('next', path);
    return NextResponse.redirect(redirectUrl);
  }

  if (user && (path === '/login' || path === '/signup')) {
    return NextResponse.redirect(new URL('/dashboard', request.url));
  }

  return response;
}

export const config = {
  matcher: ['/((?!_next/static|_next/image|favicon.ico).*)'],
};
